GET https://localhost:7241/api/Profile
###

GET https://localhost:7241/api/Profile/3

###

POST https://localhost:7241/api/Profile
Content-Type: application/json

{
  "id": 2,
  "name": "2nd "
}
###
POST https://localhost:7241/api/Profile
Content-Type: application/json

{
  "id": 3,
  "name": ""
}
###
POST https://localhost:7241/api/Profile
Content-Type: application/json

{
  "id": 4,
  "name": "4th"
}
###
POST https://localhost:7241/api/Profile
Content-Type: application/json

{
  "id": 5,
  "name": "5th"
}


###
PUT   https://localhost:7241/api/Profile
Content-Type: application/json

{
"id": 3,
  "name": "third - 3rd"

}

###

DELETE https://localhost:7241/api/Profile?Id=4

