GET https://localhost:7241/api/Profile
###

POST https://localhost:7013/graphql/ HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json

{
  flavours
 {
  style1
  style2
  //icecream
 //{
  //ic1
  //ic2
}
 }
 //}

###




GET https://localhost:7241/api/Profile?orderby=name
###

GET https://localhost:7241/api/Profile?orderby=name
###

GET https://localhost:7241/api/Profile?orderby=id desc
###

GET https://localhost:7241/api/Profile?$skip=2 & ?$top=3
###



GET https://localhost:7241/api/Profile?$select=id
###

GET https://localhost:7241/api/Profile?$select=name & $filter=name eq 'Tom' and id gt 4
###

GET https://localhost:7241/api/Profile?$select=id
###

GET https://localhost:7241/api/Profile?$filter=name eq 'Richard' and id eq 1
###

GET https://localhost:7241/api/Profile?$filter=name eq 'Richard' or id eq 2
###

GET https://localhost:7241/api/Profile?$filter=name ne 'Richard'
###

GET https://localhost:7241/api/Profile?$filter=name ne 'Richard' and id lt 3
###

GET https://localhost:7241/api/Profile?$filter=name ne 'Richard' and id gt 3
###

GET https://localhost:7241/api/Profile?$filter= contains( name, 'Richard')
###

GET https://localhost:7241/api/Profile?$filter= contains( name, 'Tom') & id gt 4
###


GET https://localhost:7241/api/Profile?$filter= name in('Tom', 'Richard')
###

GET https://localhost:7241/api/Profile/?filter=id ne 2
###

GET https://localhost:7241/api/Profile/?filter=id gt 3
###

GET https://localhost:7241/api/Profile/?filter=id ge 3
###

GET https://localhost:7241/api/Profile/?filter=id le 3
###

GET https://localhost:7241/api/Profile/?filter=id lt 3
###



POST https://localhost:7241/api/Profile/Tom
Content-Type: application/json

{
  "id": 2,
  "name": "Tom "
}
###
POST https://localhost:7241/api/Profile
Content-Type: application/json

{
  "id": 1,
  "name": "Richard"
}
###
POST https://localhost:7241/api/Profile
Content-Type: application/json

{
  "id": 2,
  "name": "Richardson"
}
###
POST https://localhost:7241/api/Profile
Content-Type: application/json

{
  "id": 3,
  "name": "Tom"
}
###
POST https://localhost:7241/api/Profile
Content-Type: application/json

{
  "id": 4,
  "name": "Richarso Smith"
}

###

POST https://localhost:7241/api/Profile
Content-Type: application/json

{
  "id": 5,
  "name": "Tom Cruise"
}

###
PUT   https://localhost:7241/api/Profile
Content-Type: application/json

{
"id": 4,
  "name": "Richard Smith"

}

###



DELETE https://localhost:7241/api/Profile?Id=2

